-- vim.lsp.start({
--    name = 'my-server-name',
--    cmd = {'name-of-language-server-executable'},
--    root_dir = vim.fs.dirname(vim.fs.find({'pyproject.toml', 'setup.py'}, { upward = true })[1]),
-- })
